Code Review for [m5-add-controllers-specs] | Dev2Dev Blog Rails Project
luigirazum/dev2dev-blog pull request #5
Opened 2023-09-05 16:55 UTC by luigirazum

# Hello Dear Code Reviewers Team 👋,
## I would like to ask for your kindly help to do the 🔍 Code Review 👀 for my project.
### The following requirements 📌 were fulfilled this time:

### - 🎯 General requirements
- [X] Make sure that there are _**no** linter errors_.
  - 🟢 `rubocop` ran and **no offenses** were detected.
- [X] Make sure that you used _**correct** flow_ `git-flow`.
  - 🟢 The <kbd>Milestone</kbd> branch `m5-add-controllers-specs` was created from `dev` to follow the `git-flow`.
- [X] Make sure that you documented your work _in a **professional way**_.
  - 🟢 All the information about the project was added to the `README.md` file, previously.

### - 🎯 Project requirements
  - [X] **Add RSpec** as a gem to your project.
    - 🟢 `rspec-rails` was previously installed.
  - [X] **Create** a Request **spec file** for all your controllers.
    - 🟢 `💾 users_controller_spec.rb` was created at `📁 spec/controllers` folder.
    - 🟢 `💾 posts_controller_spec.rb` was created at `📁 spec/controllers` folder.
  - **Make sure** that for **each action** you **check**:
    For both `UsersController` and `PostsController` `specs`
    - [X] If response status was correct.
      - 🟢 `success` http_status was received for `index` and `show` actions.
    - [X] If a correct template was rendered.
      - 🟢 `index` and `show` templates were rendered.
    - [X] If the response body includes correct placeholder text.
      - 🟢 `body` response included the correct `placeholder text` for each template.

### I really thank you for your support. 🙏
### Cheers and Happy Reviewing! 👀
### Luis 🙋‍♂️

2023-09-05 17:16 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @luigirazum,

Good job so far!
✔️ Well-written and passing tests
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-05 17:16 UTC, TedLivist commented on spec/controllers/posts_controller_spec.rb
> +RSpec.describe PostsController, type: :controller do
- [ ] Your tets should be of the `type: :request`, instead of `type: :controller`. You visit [this Microverse blog](https://www.microverse.org/blog/understanding-rspec-controller-request-specs-integration-test-using-capybara#:~:text=The%20RSpec%20team%20actually%20officially,to%20write%20request%20specs%20instead.) for more details on why we write request tests, instead of controller tests.

2023-09-05 17:16 UTC, TedLivist commented on spec/controllers/users_controller_spec.rb
> +RSpec.describe UsersController, type: :controller do
- [ ] Kindly change test type to `:request`.

2023-09-06 00:57 UTC, luigirazum commented on spec/controllers/users_controller_spec.rb
> +RSpec.describe UsersController, type: :controller do
Applied change.

2023-09-06 00:58 UTC, luigirazum commented on spec/controllers/posts_controller_spec.rb
> +RSpec.describe PostsController, type: :controller do
Tests were changed to request, as required.

2023-09-06 01:13 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @luigirazum, 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done implementing the requested changes. 🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-06 07:26 UTC, merged